#
# CI Settings for the "Reducer service" project.
#

image: node:14

stages:
  - test
  - build
  - publish

before_script:
  - npm config set registry=https://npmjs.desionlab.net/
  - npm i -g @nestjs/cli

jobTest:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - npm ci
    - npm run test

jobPublishToDesionlab:
  stage: publish
  variables:
    NODE_ENV: "production"
  before_script:
    - npx npm-cli-login -u gitlab-ci-token -p "$CI_JOB_TOKEN" -r https://npmjs.desionlab.net -e "gitlab-ci@desionlab.net"
  script:
    - npm ci
    - npm publish --access public
  only:
  - tags
