#
# CI Settings for the "Reducer service" project.
#

image: node:12

stages:
  - test
  - build
  - publish

before_script:
  - npm config set registry=https://npmjs.desionlab.net/
  - npm config set '//npmjs.desionlab.net/:_authToken' "$NPM_TOKEN"
  - npm i -g @nestjs/cli

jobTest:
  stage: test
  script:
    - npm i
    - npm run test
    - npm run build

jobPublishToDesionlab:
  stage: publish
  script:
    - npm i
    - npm run build
    - npm publish --access public
  only:
    - tags
