#
# CI Settings for the "Reducer service" project.
#

image: node:14

stages:
  - test
  - build
  - publish

before_script:
  - npm config set registry=https://npmjs.desionlab.net/
  - npm config set '//npmjs.desionlab.net/:_authToken' "$NPM_TOKEN"
  - npm i -g @nestjs/cli

jobTest:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - npm ci
    - npm run test

jobPublishToDesionlab:
  stage: publish
  variables:
    NODE_ENV: "production"
  script:
    - npm ci
    - npm publish --access public
  only:
    - tags
